### ISSUE TITLE
[!] Error: 'Chart' is not exported by node_modules/frappe-charts/dist/frappe-charts.min.iife.js, imported by node_modules/svelte-frappe-charts/src/components/base.svelte

### ISSUE THREAD

**Issue by JohnnyJayJay** [Androz2091/discord-data-package-explorer#21]
When I try to run `npm run dev`, I get the following error:
```
bundles src/main.js → public/build/bundle.js...
[!] Error: 'Chart' is not exported by node_modules/frappe-charts/dist/frappe-charts.min.iife.js, imported by node_modules/svelte-frappe-charts/src/components/base.svelte
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/svelte-frappe-charts/src/components/base.svelte (3:11)
1: <script>
2:   import { onMount, afterUpdate, onDestroy } from 'svelte';
3:   import { Chart } from 'frappe-charts';
              ^
4: 
5:   /**
Error: 'Chart' is not exported by node_modules/frappe-charts/dist/frappe-charts.min.iife.js, imported by node_modules/svelte-frappe-charts/src/components/base.svelte
    at error (/home/johnny/discord-data-package-explorer/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/home/johnny/discord-data-package-explorer/node_modules/rollup/dist/shared/node-entry.js:9824:16)
    at handleMissingExport (/home/johnny/discord-data-package-explorer/node_modules/rollup/dist/shared/node-entry.js:9725:28)
    at Module.traceVariable (/home/johnny/discord-data-package-explorer/node_modules/rollup/dist/shared/node-entry.js:10163:24)
    at ModuleScope.findVariable (/home/johnny/discord-data-package-explorer/node_modules/rollup/dist/shared/node-entry.js:8770:39)
    at FunctionScope.findVariable (/home/johnny/discord-data-package-explorer/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at ChildScope.findVariable (/home/johnny/discord-data-package-explorer/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at ReturnValueScope.findVariable (/home/johnny/discord-data-package-explorer/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at ChildScope.findVariable (/home/johnny/discord-data-package-explorer/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at Identifier$1.bind (/home/johnny/discord-data-package-explorer/node_modules/rollup/dist/shared/node-entry.js:4403:40)
```
I'm on the latest commit of the `master` branch and I ran `npm install` beforehand.\
Node version: `v14.16.0`\
NPM version: `6.14.11`

For reproduceability, this docker image also produces the error.
```
FROM node:14.16.0
WORKDIR /usr/local/app
COPY . .
RUN npm install
CMD ["npm", "run", "dev"]
```

**Comment by JohnnyJayJay** [comment]
Deleting the directory and cloning again resolved the issue. I have no idea why but I'm happy enough with that.

**Comment by TKperson** [comment]
Reinstall it did not fix my problem

**Comment by TKperson** [comment]
I have found a solution here: https://github.com/frappe/charts/issues/199

For me:
You have to go change `./node_modules/svelte-frappe-charts/src/components/base.svelte` 

from
```js
<script>
  import { onMount, afterUpdate, onDestroy } from 'svelte';
  import { Chart } from 'frappe-charts';
```
to
```js
<script>
  import { onMount, afterUpdate, onDestroy } from 'svelte';
  import { Chart } from 'frappe-charts/dist/frappe-charts.esm.js'
```
